package Frontend;



import javax.swing.*;
import java.awt.*;
import java.io.File;

public class PostPanel extends JPanel {
  private String content;
    private String imagePath;

    public PostPanel(String content, String imagePath) {
        this.content = content;
        this.imagePath = imagePath;

        // Set BoxLayout to stack components vertically (image below text)
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        // Add the text content panel first (transparent background)
        add(createTextPanel());

        // Add the image panel second (below the text)
        JPanel imagePanel = createImagePanel();
        if (imagePanel != null) {
            add(imagePanel);  // Image panel added below the text
        }
    }

    /**
     * Creates a panel for displaying the text content of the post.
     */
    private JPanel createTextPanel() {
        JPanel textPanel = new JPanel(new BorderLayout());
        JTextArea textArea = new JTextArea(content);
        textArea.setEditable(false);  // Make text area non-editable
        textArea.setLineWrap(true);  // Wrap long lines of text
        textArea.setWrapStyleWord(true);  // Ensure word wrapping is consistent

        // Make the background of the text area transparent
        textArea.setBackground(new Color(0, 0, 0, 0)); // Fully transparent background
        textArea.setForeground(Color.BLACK); // Set text color to black (or any color you want)

        // Add the text content to the text panel
        textPanel.add(new JScrollPane(textArea), BorderLayout.CENTER);
        textPanel.setOpaque(false); // Make the entire text panel transparent
        return textPanel;
    }

    /**
     * Creates a panel for displaying the image content of the post.
     * Includes error handling for missing or invalid images.
     */
    private JPanel createImagePanel() {
        if (imagePath != null && !imagePath.isEmpty()) {
            try {
                // Check if the file exists
                File imgFile = new File(imagePath);
                if (!imgFile.exists()) {
                    System.err.println("Error: Image file not found at path: " + imagePath);
                    return createErrorPanel("Image not found!");
                }

                // Load and scale the image
                ImageIcon imageIcon = new ImageIcon(imagePath);
                Image scaledImage = imageIcon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
                JLabel imageLabel = new JLabel(new ImageIcon(scaledImage));

                // Add the image to a panel
                JPanel imagePanel = new JPanel();
                imagePanel.setLayout(new FlowLayout(FlowLayout.CENTER));
                imagePanel.setOpaque(false); // Make the image panel transparent
                imagePanel.add(imageLabel);
                return imagePanel;

            } catch (Exception e) {
                // Handle unexpected errors
                System.err.println("Error loading image: " + e.getMessage());
                e.printStackTrace();
                return createErrorPanel("Failed to load image!");
            }
        }
        return null;
    }

    /**
     * Creates a panel to display an error message.
     *
     * @param errorMessage The error message to display.
     */
    private JPanel createErrorPanel(String errorMessage) {
        JPanel errorPanel = new JPanel();
        JLabel errorLabel = new JLabel(errorMessage);
        errorLabel.setForeground(Color.RED); // Display error message in red
        errorPanel.add(errorLabel);
        errorPanel.setOpaque(false); // Make error panel transparent
        return errorPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
