/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.Frontend;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import lab.Frontend.PostPanel;
import lab.Frontend.ProfilePanel;
import lab.pkg9.Content;
import lab.pkg9.Group;
import lab.pkg9.Post;
import lab.pkg9.UserManager;
import lab.pkg9.GroupAdmin;
import lab.pkg9.GroupRole;
import lab.pkg9.User;

/**
 *
 * @author Dell
 */
public class GroupPage extends javax.swing.JFrame {

    /**
     * Creates new form GroupPage
     */
    Group group ;
    User user;
    public GroupPage(Group group, User user) {
        this.group=group;
        this.user = user;
        initComponents();
       GroupRole role= user.getGroups().get(group);
               if( role instanceof GroupAdmin)
               {
                           loadAdminpage();

               }
    }

    public GroupPage() {
    }
    
public void loadGroupsPage()
{   loadGroup();
   loadposts();
    loadmembers();
    
}
public void loadAdminpage()
{
    loadGroup();
    loadposts();
    loadm
}
public void loadGroup()
{
    ProfilePanel Groupimage = (ProfilePanel) groupPhoto ;
        Groupimage.setProfileImage(group.getGroupPhoto());
         String Description = group.getDescription();

        // Set the bio text into the JTextPane
        jTextField1.setText(Description);
        jTextField1.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        
}
public void loadposts() {
    groupPosts.removeAll(); // Clear previous posts before reloading
    ArrayList<Post> posts = new ArrayList<>();

    // Collect all posts from the group
    for (ArrayList<Post> key : group.getPosts().values()) {
        posts.addAll(key);
    }

    // Sort posts by timestamp (newest first)
    Collections.sort(posts, (p1, p2) -> p2.getTimestamp().compareTo(p1.getTimestamp()));

    // Loop through each post to create panels
    for (Content post : posts) {
        String username = UserManager.findUser(post.getAuthorId()).getUsername();
        String profilePath = UserManager.findUser(post.getAuthorId()).getProfile().getProfilePhotoPath();

        // Create a PostPanel for the post
        PostPanel postPanel = new PostPanel(username, profilePath, post.getContent(), post.getImagePath());

        // Create Edit button
        JButton editButton = new JButton("Edit");
        GroupAdmin groupadmin= new GroupAdmin(group.getAdminId(), group);
        editButton.addActionListener(e -> {
            // Handle post editing logic here
            groupadmin.editPost(post.getAuthorId(), profilePath, username);
        });

        // Create Remove button
        JButton removeButton = new JButton("Remove");
        removeButton.addActionListener(e -> {
            // Handle post removal logic here
        });

        // Add buttons to the post panel
        postPanel.add(editButton);
        postPanel.add(removeButton);

        // Add the post panel to the groupPosts panel
        groupPosts.add(postPanel);
    }

    // Refresh the groupPosts panel
    groupPosts.revalidate();
    groupPosts.repaint();
}
public void loadmembers()
{
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membersPanel = new javax.swing.JPanel();
        groupPhoto = new ProfilePanel();
        groupPosts = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        createPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        membersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        membersPanel.setLayout(new javax.swing.BoxLayout(membersPanel, javax.swing.BoxLayout.Y_AXIS));

        groupPhoto.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout groupPhotoLayout = new javax.swing.GroupLayout(groupPhoto);
        groupPhoto.setLayout(groupPhotoLayout);
        groupPhotoLayout.setHorizontalGroup(
            groupPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        groupPhotoLayout.setVerticalGroup(
            groupPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        groupPosts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        groupPosts.setLayout(new javax.swing.BoxLayout(groupPosts, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Description");

        createPost.setText("Create Post");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(groupPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(createPost))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(groupPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(membersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(groupPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(createPost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(membersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupPosts, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPost;
    private javax.swing.JPanel groupPhoto;
    private javax.swing.JPanel groupPosts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel membersPanel;
    // End of variables declaration//GEN-END:variables
}
