/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.Frontend;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import lab.pkg9.Group;
import lab.pkg9.UserManager;
import lab.pkg9.GroupAdmin;

/**
 *
 * @author Mahmoud Waleed
 */
public final class nextAdmin extends javax.swing.JFrame {

    private final Group group;
    private final GroupAdmin groupAdmin;

    public nextAdmin(Group group, GroupAdmin groupAdmin) {
        setContentPane(new JLabel(new ImageIcon("R (2).jpg")));
        this.group = group;
        this.groupAdmin = groupAdmin;
        initComponents();
        displayUsers(group);
    }

    /**
     * Creates new form nextAdmin
     *
     * @param group
     */

    public void displayUsers(Group group) {
        for (String userId : group.getUsers().keySet()) {          
            JPanel entryPanel = displayUser(userId);
            nextAdminContainer.add(entryPanel);          
        }   
        nextAdminPanel.repaint();
        nextAdminPanel.revalidate();
    }

    
    private JPanel displayUser(String userId){
        String profileImagePath = (group.getGroupPhoto() != null)
                    ? group.getGroupPhoto()
                    : null;
            EntryPanel entryPanel = new EntryPanel(UserManager.findUser(userId).getUsername(), profileImagePath);
            entryPanel.setPreferredSize(new Dimension(200, 100));
            JButton choose = new JButton("Choose");        
            choose.addActionListener(evt -> {
                groupAdmin.leaveGroup(userId);
                dispose();
            });
            entryPanel.add(choose);
            return entryPanel;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nextAdminPanel = new javax.swing.JScrollPane();
        nextAdminContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("         Choose Next Admin");

        nextAdminContainer.setLayout(new javax.swing.BoxLayout(nextAdminContainer, javax.swing.BoxLayout.Y_AXIS));
        nextAdminPanel.setViewportView(nextAdminContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextAdminPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel nextAdminContainer;
    private javax.swing.JScrollPane nextAdminPanel;
    // End of variables declaration//GEN-END:variables
}
