/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.Frontend;

import javax.swing.JButton;
import javax.swing.JLabel;
import lab.pkg9.Group;
import lab.pkg9.UserManager;

/**
 *
 * @author Mahmoud Waleed
 */
public class nextAdmin extends javax.swing.JFrame {
     private Group group;

    public nextAdmin(Group group) {
        this.group = group;
    }
    /**
     * Creates new form nextAdmin
     */
    public nextAdmin() {
        initComponents();
    }
    public void displayUsers(Group group){
        for(String userID: group.getUsers().keySet()){
            JLabel userName = new JLabel();
            userName.setText(UserManager.findUser(userID).getUsername());
            JButton choose = new JButton("Choose");
            nextAdminContainer.add(userName);
            nextAdminContainer.add(choose);
            nextAdminPanel.add(nextAdminContainer);
            nextAdminContainer.repaint();
            nextAdminContainer.revalidate();
        }
            nextAdminContainer.repaint();
            nextAdminContainer.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nextAdminPanel = new javax.swing.JScrollPane();
        nextAdminContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("         Choose Next Admin");

        nextAdminContainer.setLayout(new javax.swing.BoxLayout(nextAdminContainer, javax.swing.BoxLayout.LINE_AXIS));
        nextAdminPanel.setViewportView(nextAdminContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(nextAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel nextAdminContainer;
    private javax.swing.JScrollPane nextAdminPanel;
    // End of variables declaration//GEN-END:variables
}
