/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab.Frontend;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import lab.pkg9.FriendshipServiceInterface;
import lab.pkg9.User;

/**
 *
 * @author DELL
 */
public class SuggestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuggestionPanel
     */
    public SuggestionPanel() {
        initComponents();
    }
public SuggestionPanel(User sender, User reciever, String profileImagePath, FriendshipServiceInterface Fm) {

    // Profile Image
    ProfilePanel profilePanel = new ProfilePanel();
    profilePanel.setPreferredSize(new Dimension(70, 70)); // Profile image size
    if (profileImagePath != null && !profileImagePath.isEmpty()) {
        File imgFile = new File(profileImagePath);
        if (imgFile.exists()) {
            profilePanel.setProfileImage(imgFile.getAbsolutePath());
        }
    }
    add(profilePanel);

    // Panel for username and button
    JPanel detailsPanel = new JPanel();
    detailsPanel.setLayout(new BoxLayout(detailsPanel, BoxLayout.Y_AXIS)); // Vertical alignment
    detailsPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 0)); // Padding around text

    // Username Label
    //String name = reciever.getUsername();
    //JLabel usernameLabel = new JLabel(name);
    //usernameLabel.setFont(new Font("Arial", Font.PLAIN, 15)); // Font size
    //usernameLabel.setAlignmentX(Component.LEFT_ALIGNMENT); // Align to the left
    //detailsPanel.add(usernameLabel);



    add(detailsPanel);

   
    // Reduce panel padding
    setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
